### PR TITLE
fix(props): reactive

### PR DESCRIPTION
**Pull request by aoor9**
### Type of change
*  Breaking change (fix or feature that would cause existing functionality to change)

### Description
I noticed that some prop values (eg. label, url etc.) are immutable, once set, which is frustrating. In some cases, I need to change those settings dynamically, especially when I globally share the component in my app. But any method I tried to update the needed props was pointless, as long as the component prevents this, and I see no reason why.

For example, the `url` prop, when `undefined`, it gets the URL from the browser and keeps that value until an app reload, which is not good.

Let's suppose I have the component inside `app.vue`
```
<template>
  <SocialShare
    network="facebook"
    styled="true"
    label="false"
    :url="currentUrl"
   />
</template>

<script setup lang="ts">
const currentUrl = ref<string | undefined>(undefined)
</script>
```

where `url` gets the app link with current path (so initializing it with `undefined` is fine), and I expect it to update its value whenever and wherever I need, like on page change event, from `/index` to `/about`.

If I try to change it manually
`currentUrl.value = "whatever url string I have in mind"`
or while watching the `useRoute` composable, the component gets unaffected.

Same for `label` (I fixed it first because it was easier), when I wanted it dynamically based on screen mode, like showing it on desktop and hiding it on mobile.

### 📝 Checklist
* [x]  Make `label` reactive
* [x]  Make `url` reactive

### CODE REVIEW

**Comment by stefanobartoletti** [comment]
Thanks for opening this, can you please provide some more context so I can better understand the use cases, and maybe a working example to test it myself?

Do you just need these values to be reactive?

Also, I see that there is an edit in https://github.com/stefanobartoletti/nuxt-social-share/pull/159/files#diff-c263b8042c6101dc0038fc1bf7e3d722ca34d14882a069fc53b8699d4b1a8400 that does not seem to be related.

**Comment by aoor9** [comment]
@stefanobartoletti Updated the message and removed the edits unrelated to the issue.

**Comment by stefanobartoletti** [comment]
Thanks, it is a bit clearer now, but If you could provide a reproduction it would help to better place all these things in context and allow me to directly see and test it. 

As a side note, it is always better to open issues to discuss the situation before opening a possibly breaking PR, it would make all the process smoother for everyone.

**Comment by aoor9** [comment]
I hope this will be clear enough

**Comment by stefanobartoletti** [comment]
Ok it is a bit clearer now.

If you want to go on and implement the other properties too we can then review the changes together later.

**Comment by aoor9** [comment]
I pushed another code change, for url option, and I don't know whether it's an optimal one, I spent 2 days to make it work (you can see the updated playground).

>Please also run eslint to check for errors and code styling issues.

I'm linting the code, although there is no settings for VS Code. Making some and adapt the existing eslint rules to them, so you can lint the code on file save, might be less painful than running the command on terminal.

**Comment by aoor9** [comment]
Can you please review it?

**Comment by stefanobartoletti** [comment]
Thanks for the contribution, but at a first glance I see far too many edits and unnecessary line breaks that change the formatting without actually altering the code.

In the current state, it is very difficult to tell apart new code from what is only a different formatting from the source codebase (that, to be honest, are not desired edits)

It is very difficult in the current state to properly evaluate what this PR is doing and how it is implementing the changes. At the moment I'm quite busy with my work, I don't have the necessary time and concentration to go through this.

**Comment by stefanobartoletti** [comment]
Closing this as it has not received improvement and it is not up-to-date with the latest releases.

If the issue persists, a new issue can be opened.

**Pull request closed without merging**
